baseurl = "/"
languageCode = "en-us"
title = "Brian Barkley's website"
theme = "hugo-lithium"


googleAnalytics = ""
disqusShortname = ""


ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About Brian"
    url = "/about/"
[[menu.main]]
    name = "github.com/BarkleyBG"
    url = "https://github.com/BarkleyBG"
[[menu.main]]
    name = "twitter.com/BarkleyBG"
    url = "https://twitter.com/BarkleyBG"

[params]
    description = "Brian Barkley's personal website, built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"
    
    ## default author and date
    author = "Brian Barkley"
    dateFormat = "2006/01/02"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

    
## References

# blogdown website's section on configuration: https://bookdown.org/yihui/blogdown/configuration.html

