---
title: "Hack & Tell: Data Science in MKE"
author: "Brian G. Barkley"
date: '2019-01-26'
slug: "hack-n-tell-2019-jan"
categories: ["blogdown", "Milwaukee"]
tags: ["blogdown", "Milwaukee", "hack & tell"]
---

This website is now live! I spent several hours at [Rokkincat's Hack & Tell](https://www.rokkincat.com/hack-n-tell/) reading more about blogdown and netflify, and toying with a few settings. 

One big thing that I've been wanting to do is start a [catalogue of the data science activities in Milwaukee](/DS4MKE/). There is a lot of beauty in Milwaukee, and also a lot of need. The MKE community also has many talented professions working Saturdays on side projects and hobbies that make Milwaukee a better place. I hope we can connect our skills to work together to bring more good to Milwaukee!

## Data Science 4 MKE Good:

Check out the [Data Science 4 Milwaukee page](/DS4MKE/) on my site for more information on interesting data projects around MKE. Contact the organizers of these projects to get involved. Bring your talents, or work on new ones. 

I hope to keep updating that page over time. If you have any questions, please contact me!



## Setting up my first blogdown site

If you're interested in how blogdown works, much of the information I learned came from the [blogdown book](https://bookdown.org/yihui/blogdown/). Here are some other pieces of note as I setup my site:

- Tinkering with HTML settings was fun, but not very productive. I don't know much HTML or CSS, so trying to make things really pretty was difficult and often unsuccessful. If you're just starting a new blog and frustrated with the HTML settings, I'd recommend focusing on writing content!
- I'm hosting on Netlify's free site for now, which was easy to setup:
  - Open Rstudio [and start a `new_site()`](https://bookdown.org/yihui/blogdown/a-quick-example.html)
  - Changed my logo by replacing the image in `hemes/hugo-lithium/static/images/logo.png`
    - Note that the `public` folder is created by settings in other directories, like `themes` and `content`. For example, change a line in `public/index.html` and re-build the site... does your edit disappear?
  - I'm using Git & GitHub to post my site. After a `git init`, I saved my new site in a commit, and then pushed everything to a new GitHub repo, https://github.com/BarkleyBG/BarkleyBG.netlify.com.
  - I followed instructions to [deploy with Netlify](https://bookdown.org/yihui/blogdown/netlify.html). I am using a free site, and I think the only small part was to select the new repo from a drop-down in Netlify. 
  - Any commits pushed to master on GitHub are showing up a few seconds later on my website, so I think I'm all set!
  
If you have any questions as you set up your first blogdown-netlify site, please tweet or email me. 

### Future improvements

- I'll need to turn disqus commenting on. Please get in touch with me otherwise!
- I'd like to add static content above the blogroll on the splash page. Suggestions welcome :-)
- Other improvements like Google Analytics will probably happen someday...

## What is Hack & Tell?

Here's more information about the [Hack & Tell series](https://www.rokkincat.com/hack-n-tell/):

> Hack & Tell is an eight hour event in which a bunch of people sit in the same room, eat delicious food, and make something. There is no need for business models, customer validation, or precise pitches with highly designed slide decks.

> The purpose of this hackathon is to hang out and team up with other developers and designers for the sake of making something awesome.

> Anyone [can come]. Anyone who knows how to code, how to design, or wants to work on something they think is cool. If you don't know any of the above, you can spend the time learning how, and showing everyone what you learned. That's great too!



## Thanks, awesome people:

Thanks go out to:

- [Rokkincat](https://www.rokkincat.com/) for organizing the [Hack & Tell series](https://www.rokkincat.com/hack-n-tell/), which is really great
- [Northwestern Mutual](https://nm.engineering/) for supplying [Colectivo coffee](http://colectivocoffee.com/) & breakfast, and also a burrito lunch
- [Ward4](https://www.ward4mke.com/) co-working space for providing a beautiful setting in the [Pritzlaff building](https://urbanmilwaukee.com/building/pritzlaff-building/)