---
title: "Announcing the WeCountCOVID19.com Survey (Part 1)"
author: "Brian G. Barkley"
date: '2020-04-21'
slug: announcing-the-wecountcovid19-com-survey
categories: ["Milwaukee", "COVID19", "Code for Milwaukee", "WeCountCOVID19.com"]
tags: ["Milwaukee", "COVID19", "Code for Milwaukee", "WeCountCOVID19.com"]
---

I am excited to announce that **the [WeCountCOVID19.com](www.WeCountCOVID19.com) survey is live!**

I'm so excited for this, in fact, that I'm writing a blog post for the first time in more than a year! Skip down to to bottom to learn about how the survey came to be, and my work with [Code for Milwaukee](https://codeformilwaukee.org/).

## About the [WeCountCOVID19.com](www.WeCountCOVID19.com) survey

The [WeCountCOVID19.com](www.WeCountCOVID19.com) survey aims to count every single Wisconsinite who is possibly infected by the coronavirus. It is a "symptom survey", asking basic questions about how you're feeling and how long you've been ill. **The survey is anonymous, takes 5 minutes, and you can take it from your computer or mobile device**. 

So my big request is:

- **If you're sick, please take this survey!**
- **If you're not sick, please share the survey with your friends and family!**

Thank you for helping to promote this survey. We need more responses to help uncover where and what the symptoms of COVID-19 are. When you visit [WeCountCOVID19.com](www.WeCountCOVID19.com), you'll notice that **we are creating analysis reports and sharing results of from the survey.**

Why should you care? The survey is important because every voice counts. We ALL count. This survey aims to help individuals' voices be heard by policymakers, government officials, loca business owners, and anyone who visits the website. 

---
This blog post is the first in a many-part series about the WeCountCOVID19.com survey. In the future I hope to write about topics including:

- The origin of the WeCountCOVID19.com survey
- How we built a team of volunteers to analyze and publish the survey
- My role and what I've learned from organizing the survey's team of excellent volunteers
- Exciting new features on the WeCountCOVID19.com website

---
About Code for Milwaukee



In this time, I've been volunteering lots of my time as a co-founding member and the Communications Lead at [Code for Milwaukee](www.codeformilwaukee.org), which is Wisconsin's only Code for America brigade. I've updated this blog site with information on Code for Milwaukee [in the header](https://barkleybg.netlify.app/ds4mke/). 

Among many other events Code for Milwaukee hosts a Hack Night on the Third Thursday of every month. A list of all CfM events is [on our Meetup page](https://www.meetup.com/Code-for-Milwaukee/events), and anyone is welcome.

Please follow our meetup page, or RSVP to an upcoming event. I hope to see you there soon! Until then, find more information at [https://codeformilwaukee.org/](https://codeformilwaukee.org/) or follow [`@codeformke`](https://twitter.com/codeformke) on twitter.





